services:
  yt-dlp:
    tty: true
    volumes:
      - ${DATA_DIR}:/data
    cap_add:
      - NET_ADMIN
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    environment:
      - PUID=1000
      - PGID=1000
    build: .
